apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-demo-app
spec:
  template:
    spec:
      containers:
        - name: app
          env:
            - name: ENVIRONMENT
              value: dev
