apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

patches:
  - path: patch-deployment.yaml
  - path: patch-service.yaml

replicas:
  - name: harness-demo-app
    count: 2

images:
  - name: harness-demo-app
    newName: docker.io/sharmaamanrajesh/harness-demo-app
    newTag: "bootstrap"
