apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base
  - poddisruptionbudget.yaml

patches:
  - path: patch-deployment.yaml
  - path: patch-service.yaml

replicas:
  - name: harness-demo-app
    count: 3

images:
  - name: harness-demo-app
    newName: docker.io/sharmaamanrajesh/harness-demo-app
    newTag: "931c1d2066134dde998433002902d36aaa2d92a2"
