apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base
  - poddisruptionbudget.yaml

patches:
  - path: patch-deployment.yaml
  - path: patch-service.yaml

replicas:
  - name: harness-demo-app
    count: 3

images:
  - name: harness-demo-app
    newName: docker.io/sharmaamanrajesh/harness-demo-app
    newTag: "27d5dc227030c7f76d01ea69c5f4cb0e9a834f3b"
